# site settings
title: Ciberseguridad para personas
subtitle: Adquiriere hábitos seguros en el ciberespacio
email: ciberseguridad@asesoreducativo.mx
description: Capacítate para adoptar mejores prácticas y hábitos seguros en tus actividades en línea.
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://ciberseguridad.asesoreducativo.mx/ # the base hostname & protocol for your site
author:
street_address: 
city: Mexicali
state: Baja California
zip_code: 
country: México
phone: 686 946 2551

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
